<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.duoc.bancoxyz</groupId>
        <artifactId>banco-xyz-bff</artifactId>
        <version>1.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>core-client</artifactId>
    <name>core-client</name>
    <description>Cliente del contrato publicado por core-banking-api</description>

    <dependencies>
        <dependency>
            <groupId>com.duoc.bancoxyz</groupId>
            <artifactId>core-contrato</artifactId>
        </dependency>
        <dependency>
            <groupId>com.duoc.bancoxyz</groupId>
            <artifactId>seguridad-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
</project>
